[package]
name = "control_flow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base_lib = { path = "../../librarys/base_lib"}
io_control = {path = "../../librarys/io_control"}