[package]
name = "use_crate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = {version = "0.3.13", features=["macros"] } 
build_crate = { path="../build_crate" }